# Generated by Django 4.0.4 on 2022-06-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningSets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
