# Generated by Django 4.0.4 on 2022-06-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningSets', '0002_alter_set_options_alter_question_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
